### ISSUE TITLE
Public key derivation fails

### ISSUE THREAD

**Issue by leahcornelius** [witnet/vrf-rs#23]
I am using https://crates.io/crates/secp256k1, to create secp2561k keypairs and then this lib to make VRF's around them. However, the public key derived using this lib is different from the one in secp2561k. Am I doing something wrong on my end?

**Comment by leahcornelius** [comment]
Apologies, was passing incorrect stuff to your functions. Sorry for the bother, have a pleasant evening!

**Comment by aesedepece** [comment]
No problem!
