### ISSUE TITLE
Expose openssl's vendored feature

### ISSUE THREAD

**Issue by leahcornelius** [witnet/vrf-rs#28]
First off i love the library. However, to cross-compile I must employ openssl's vendored feature. Unlike most crates that depend on it you have not exposed this (https://docs.rs/openssl/latest/openssl/). Would you be able to expose this transitive dependency feature under a name like "openssl-vendored" so I could so something like:
vrf = { version = "0.1.0", features = ["openssl-vendored"] }

**Comment by HenricoW** [comment]
Hi @leocornelius, could you find any work-around in the mean time?

I have the same issue and I'm stuck :(

**Comment by aesedepece** [comment]
@leocornelius @HenricoW The `vendored` feature is now supported in version `0.2.4`. Sorry for the delay!
