### ISSUE TITLE
Compile error openssl-sys v0.9.72

### ISSUE THREAD

**Issue by Dzhegash** [witnet/vrf-rs#29]
I can't compile the project due to an error: failed to run custom build command for `openssl-sys v0.9.72`

How to fix it? I tried adding crates:
openssl = { version = "0.10.38", features = ["vendored"] }
openssl-sys="0.9.72"
But it didn't work.

My env:
OS: Windows7
CPU: Intel Core i5
Rust(stable): rustc 1.58.1

**Comment by aesedepece** [comment]
This is apparently a duplicate of #28. Thanks for reporting @Dzhegash!
